### ISSUE TITLE
SliderUnlocker doesn't work in school exploring mode in the main game 

### ISSUE THREAD

**Issue by CodyLTH** [IllusionMods/BepisPlugins#69]

**Comment by ManlyMarco** [comment]
I had a look at it multiple times at different points in time and I don't see why it would fail to work.

**Comment by Timo713** [comment]
To this matter, I've kept a version of KK_ForceHighPoly 1.0 (yes, the first version) which makes it possible to load SliderUnlocker values above 100 and below 0 in the overworld as they are in the maker/scene. It's just way too laggy and crashes the game sometimes when loading H, but still, I prefer that than not be able to see the characters correctly.

Looks like the problem doesn't affect all the sliders, for example, heights below 0 and KKABMX values still load fine (I tested it with KK_ForceHighPoly 1.2) So maybe that could help solve the problem, or by using that part of the code in KK_ForceHighPoly 1.0 that makes it possible to load all the sliders.

**Comment by ManlyMarco** [comment]
Are you sure that KK_ForceHighPoly 1.0 makes all sliders work, while all newer versions no longer do (including 1.1)?

**Comment by Timo713** [comment]
Not sure if all the sliders work since I haven't tested them all, but to this moment, every one I checked works (Breast Size/Hips/Butt etc.) And yup, the problem started in 1.1, only 1.0 works. It's strange, I know.

Actually, I think the only Slider working off limits in 1.2 is the height value.

Just in case you want to test it, I'll put it here, since I don't know if there is a way to get the older ones from DeathWeasel's git.
[KK_ForceHighPoly.zip](https://github.com/IllusionMods/BepisPlugins/files/4197107/KK_ForceHighPoly.zip)

**Comment by ManlyMarco** [comment]
Thanks for the info! Can you try this build? It should fix the sliders in both normal and hipoly modes. 
[SliderUnlocker.zip](https://github.com/IllusionMods/BepisPlugins/files/4199352/SliderUnlocker.zip)

**Comment by Timo713** [comment]
Ok, I checked it, still the same. Again, only the height value seems to work with or without 1.2. Also noticed that some KKABMX may still be affected (still present in previous build), here is a comparison between lowpoly, 1.0, 1.2 and the maker in a heavily modified SliderUnlocker and KKABMX char. 

[comparison.zip](https://github.com/IllusionMods/BepisPlugins/files/4202037/comparison.zip)

Thanks for the effort anyway, I'll keep testing if something else is changed.

**Comment by ManlyMarco** [comment]
Try this build, it should work now. [SliderUnlocker.zip](https://github.com/IllusionMods/BepisPlugins/files/4202194/SliderUnlocker.zip)

**Comment by Timo713** [comment]
It works! Thank you so much! Lowpoly still has some weirdness/distortions here and there, and some sliders aren't working yet, but I think most are now. I always use highpoly, so that's no problem for me, but I can still help by testing lowpoly.

Here is a how lowpoly looks now on this character: 

![Koikatu-2020-02-13-19-47-47-UI](https://user-images.githubusercontent.com/60951827/74497334-ff1d4c00-4ea2-11ea-8b40-e09ba31b5fa3.jpg)

**Comment by ManlyMarco** [comment]
The low poly model has a slightly different bone structure so that's likely the cause of the distortions. I think this is as good as it will be with the current setup.

Thank you for the help! I could fix this only because you noticed that it worked with KK_ForceHighPoly 1.0.
